<a href="https://colab.research.google.com/github/arrurisiddartha/ICP-3/blob/main/ICP_3_Part_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
#1. Reshape the array to 3 by 5
#2. Print array shape.
#3. Replace the max in each row by 0
#Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

import numpy as np

# Step 1: Create a random vector of size 15 with integers between 1 and 20
random_vector = np.random.randint(1, 20, size=15)

# Step 2: Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Step 3: Print array shape
print("Array shape: ", reshaped_array.shape)

# Step 4: Replace the max in each row by 0
reshaped_array[np.arange(reshaped_array.shape[0])[:, np.newaxis], reshaped_array.argmax(axis=1)[:, np.newaxis]] = 0

# Print the updated array
print(reshaped_array)

# Create a 2-dimensional array of size 4 x 3
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print the shape, type, and data type of the array
print("Array shape: ", array_4x3.shape)
print("Array type: ", type(array_4x3))
print("Array data type: ", array_4x3.dtype)

In [ ]:
#b. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
#[[3-2]
#[10]]

import numpy as np

# Given square array
A = np.array([[3-2j, 0], [10, 0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nRight eigenvectors:")
print(eigenvectors)

In [ ]:
#c. Compute the sum of the diagonal element of a given array.
#[[012]
#[3 4 5]]

import numpy as np

# Given array
A = np.array([[1, 2], [3, 4], [5, 0]])

# Compute sum of diagonal elements
diagonal_sum = np.trace(A)

# Print diagonal sum
print("Sum of diagonal elements: ", diagonal_sum)


In [ ]:
#d. Write a NumPy program to create a new shape to an array without changing its data.
#Reshape 3x2:
#[[12]
#[34]
#[56]]
#Reshape 2x3:
#[[123]
#[456]]

import numpy as np

# Given array
A = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to 3x2
A = A.reshape(3, 2)

# Print the reshaped array
print("3x2 array:")
print(A)

# Reshape the array to 2x3
A = A.reshape(2, 3)

# Print the reshaped array
print("\n2x3 array:")
print(A)